%%
% open the *.node file of the unsturcetured mesh generated by the TetGen
fid1 = fopen('c:/modeling/dc/tetgen1.4.3/tetgen1.4.3/xsmt2.1.node', 'r');

tline=fgetl(fid1);
val=sscanf(tline,'%d');
nnode=val(1);
x=zeros(nnode,1)+NaN;
y=zeros(nnode,1)+NaN;
z=zeros(nnode,1)+NaN;
for i=1:nnode
    tline=fgetl(fid1);
    val=sscanf(tline,'%f');
    x(i)=val(2);
    y(i)=val(3);
    z(i)=val(4);
end

% open the *.ele file of the unsturcetured mesh generated by the TetGen
fid2 = fopen('c:/modeling/dc/tetgen1.4.3/tetgen1.4.3/xsmt2.1.ele', 'r');

tline=fgetl(fid2);
val=sscanf(tline,'%d');
nele=val(1);
emap=zeros(4,nele)+NaN;
%irg=zeros(nele)+NaN;
for i=1:nele
    tline=fgetl(fid2);
    val=sscanf(tline,'%d');
    emap(1,i)=val(2);
    emap(2,i)=val(3);
    emap(3,i)=val(4);
    emap(4,i)=val(5);
    irg(i)=val(6);
end

% open the *.ele file of the unsturcetured mesh generated by the TetGen
%fid3 = fopen('c:/modeling/dc/tetgen1.4.3/tetgen1.4.3/mt1d.a.node', 'r');

%tline=fgetl(fid3);
%val=sscanf(tline,'%d');
%nsite=val(1);
%xsite=zeros(nsite,1)+NaN;
%ysite=zeros(nsite,1)+NaN;
%zsite=zeros(nsite,1)+NaN;

%for i=1:nsite
%    tline=fgetl(fid3);
%    val=sscanf(tline,'%f');
%    xsite(i)=val(2);
%    ysite(i)=val(3);
%    zsite(i)=val(4);
%end

vol=zeros(nele,1)-1;

fid4=fopen('c:/modeling/dc/tetgen1.4.3/tetgen1.4.3/xsmt2.1.vol','w');
fprintf(fid4, '%d\n', nele);
for i=1:nele
    n1=emap(1,i);
    n2=emap(2,i);
    n3=emap(3,i);
    n4=emap(4,i);
    n5=irg(i);
    xc=(x(n1)+x(n2)+x(n3)+x(n4))/4.0;
    yc=(y(n1)+y(n2)+y(n3)+y(n4))/4.0;
    zc=(z(n1)+z(n2)+z(n3)+z(n4))/4.0;
    del=abs((x(n2)-x(n1))*(y(n3)*z(n4)-z(n3)*y(n4))+(x(n1)-x(n3))*(y(n2)*z(n4)-z(n2)*y(n4))+(x(n4)-x(n1))*(y(n2)*z(n3)-z(n2)*y(n3))+(x(n3)-x(n2))*(y(n1)*z(n4)-z(n1)*y(n4))+ (x(n2)-x(n4))*(y(n1)*z(n3)-z(n1)*y(n3))+(x(n4)-x(n3))*(y(n1)*z(n2)-z(n1)*y(n2)))/6.0;
    if (xc>=-10000)&&(xc<=10000)&&(yc>=-15000)&&(yc<=15000)&&(zc>0)&&(zc<15000)
                 vol(i)=del/2.0;   
    end
%      if(n5==4)
%          vol(i)=4500;
%      end
    fprintf(fid4, '%d  %f\n', i,vol(i));
end

fclose(fid1);
fclose(fid2);
%fclose(fid3);
fclose(fid4);                
            


